kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
  - name: pull
    image: omerxx/drone-ecr-auth
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
  - name: test
    image: r-dev-ci:4.1.0
    commands:
      - go mod tidy
      - go mod download
      - go test -v ./...
  - name: lint
    image: golang:1.16
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - golangci-lint run
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
  - name: go
    temp: { }